apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-admin
subjects:
- kind: ServiceAccount
  name: pipeline-admin
  namespace: ci-cd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io