apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
  name: push-to-edge
spec:
  params:
  - name: MODEL_VERSION_DIGEST
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: push-to-edge-
      labels:
        app-name: push-to-edge
    spec:
      params:
        - name: MODEL_VERSION_DIGEST
          value: $(tt.params.MODEL_VERSION_DIGEST)
      pipelineRef:
        name: push-to-edge
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
        - name: edge-pipeline-pvc
          persistentVolumeClaim:
            claimName: build-embeded-model-app