apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: camera
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: camera
  namespace: fedora-detection-edge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-camera-detection
  labels:
    app: remote-camera-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-camera-detection
  template:
    metadata:
      labels:
        app: remote-camera-detection
    spec:
      serviceAccountName: camera
      containers:
      - name: remote-camera-detection
        image: quay.io/alegros/remote-camera-detection:v2 # CHANGEME with the image created automatically by your SNO arm cluster.
        securityContext:
          privileged: true
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: remote-camera-detection
spec:
  selector:
    app: remote-camera-detection
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: remote-camera-detection
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: remote-camera-detection