apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-s3-creds
  namespace: fedora-detection-prod
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: s3-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: fedora
  AWS_S3_ENDPOINT: http://minio-pipelines-definition.fedora-detection:9000/
  AWS_SECRET_ACCESS_KEY: minio123